## Lab 1 part 2
Congratulations on successfully forking the lab and pulling it down. Now we can begin to do science. 

In this lab you will:
* Become familar with numpy arrays and indexing. (this will likely be a refresher)
* Play with a real astronomical image.
* Extract data from that image, called the flux.

This content is contained in what is called a Jupyter "cell".
(Double click on this cell until the text changes. This language is called Markdown.)

### This lab is meant to be completed one cell at a time. You can evaluate each cell by pressing shift+enter. This contains a mix of cells that are instructional, and cells where I want you and your group members to collaborate on finding a solution. Problems will be indicated like this:

### Problem N:

In [1]:
# Some description of the problem. Insert your solution in this cell or between the cell above and below

End of problem N

### Refreshers: Numpy arrays and importing in Python

In [2]:
# We need to use numpy. In particular, things called arrays. 
# That is what numpy specializes in.
# Also, in python, anything preceded by a # is a comment. 
# Let us try to load in numpy, in particular, the arange function:
# https://numpy.org/doc/stable/reference/generated/numpy.arange.html

numpy.arange(5)

NameError: name 'numpy' is not defined

### Problem 1:

Why didn't the above cell work? Discuss and put your best (1 sentence) guess below (change the set cell type to Markdown):

In [28]:
# REMOVE
#This did not work because the jupyter notebook does not yet know what
# numpy means.

End of problem 1.

In [4]:
# Now lets do something that works:
import numpy
# this imports the numpy module, meaning now you can use it.
# Everything we use in python has to first be "imported" before we can use it.

In [5]:
print(numpy.arange(5))


[0 1 2 3 4]


In [11]:
# also notice print(). Print() will print the output to console of any items you place within
# the parenthesis().
print('print can be useful for debugging code. But "pdb" is better for that, as we will later discuss.')

print can be useful for debugging code. But "pdb" is better for that, as we will later discuss.


In [6]:
# Yay! It worked. Arange creates an array of numbers up 
# to (but excluding) the number you choose.
# for instance, lets say I want an array from 5 to 9:
print(numpy.arange(5, 10))

[5 6 7 8 9]


In [12]:
# Note that when I say array, I mean a very specific thing that is
# an array. 
# In more detail, we can see this by assigning these things to variables.
an_array = numpy.arange(5, 10)
a_list = [5, 6, 7, 8, 9]

print(an_array)
print(a_list)

[5 6 7 8 9]
[5, 6, 7, 8, 9]


In [20]:
# the array and list look almost identical, but they are two different
# python things:
print(type(an_array))
print('so this ^^ is an numpy.ndarray, or array for short.')
print(type(a_list))
print('while this ^^ is a python List')
print('P.S. type() just prints the type of whatever is in the parenthesis')
print('So in some mystical world, I might do type(duck) and get back:')
print('type(duck) = <class `bird`>')

<class 'numpy.ndarray'>
so this ^^ is an numpy.ndarray, or array for short.
<class 'list'>
while this ^^ is a python List
P.S. type() just prints the type of whatever is in the parenthesis
So in some mystical world, I might do type(duck) and get back:
type(duck) = <class `bird`>


In [21]:
# Lets get back to numpy and imports though.
# I get tired of writing "numpy", so lets shorten things:
import numpy as np
# the "as" statement will import the entire package, but with a nickname. Any nickname works.
np.arange(5, 10)
# also notice that in jupyter, it will always display the output of the last line in a cell

array([5, 6, 7, 8, 9])

In [8]:
import numpy as somenickname
somenickname.arange(5, 10)

array([5, 6, 7, 8, 9])

In [22]:
# numpy has a rich amount of functionality. For instance, lets generate a random number that is either 0 or 1:
np.random.randint(0, 2)

1

### Problem 2:

read the documentation for numpy randint.
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
create (in the cell below cell) code that gives me an array 
with random numbers between 4 and 6 (so either 4 or 5), and is length 5.
so something like [4, 5, 4, 4, 5]
Note that all the numbers might end up being 4 or 5. It is random after all !

Hint: look for size and shape.

In [34]:
# REMOVE
np.random.randint(low=4, high=6, size=5)

array([4, 5, 5, 5, 4])

End of problem 2

In [36]:
# you can also do what is called "slicing" to numpy array objects.
# You cannot slice a list type object. 
# Slicing will give you a portion of a numpy array. 
# For example:
a = np.arange(10, 20) # make an array of 0,1,...,9
slice_first_five = a[0:5]
slice_element_five_thru_9 = a[5:10]
print(slice_first_five)
print(slice_element_five_thru_9)
# Note that I used a[5:10] to get elements 5 through 9. That is because the last locator of the slice (10) is
# exclusive. Meaning I will get up through element 10 - 1 = 9.
# Also that in python, everything is indexed from zero. So element 0 is the first element of the list and so forth.


[10 11 12 13 14]
[15 16 17 18 19]


In [51]:
# And we can do all of this in two dimensions (and more).
# lets make a 2d numpy array:
my_2d_array = np.ones((4, 4))
print(my_2d_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [52]:
# For later reference, this cell is named: slicing cell 1.
# and we can slice it.
# I am going to do a couple fancy things just to make the matrix more identifiable for you.
my_2d_array *= np.arange(4)*np.arange(1, 5).reshape(-1, 1)
print(my_2d_array)

[[ 0.  1.  2.  3.]
 [ 0.  2.  4.  6.]
 [ 0.  3.  6.  9.]
 [ 0.  4.  8. 12.]]


In [58]:
# For later reference, this cell is named: slicing cell 2.
# first lets get the rows (what is called the first axis, or zeroth axis)
print(my_2d_array[0])
print(my_2d_array[1])

[0. 1. 2. 3.]
[0. 2. 4. 6.]


In [60]:
# For later reference, this cell is named: slicing cell 3
# Now lets slice along the columns
# first lets get the rows (what is called the first axis, or zeroth axis)
print(my_2d_array[:, 1])
print(my_2d_array[:, 2])

[1. 2. 3. 4.]
[2. 4. 6. 8.]


### Problem 3:

In [61]:
# problem 3.1
# In slicing cell 1, I did:
# my_2d_array *= some stuff
# what is *= equivalent to? Google it and write the answer in the cell below.

# problem 3.2
# Run the cell with *= again. Just pressing shift enter in it. what happened to the array? Is this what
# you expected?

# problem 3.3:
# In slicing cell 3, what rows are my_2d_array[:, 1] and my_2d_array[:, 2] ? What does ":" tell python to do?
# What happens if I type my_2d_array[0, 1]? What is that?
#

3.1:

3.2:

3.3:  

End of problem 3

## End of refreshers: Getting portions of an image.

### Problem 4:

In [1]:
# Some description of the problem. Insert your solution in this cell or between the cell above and below

End of problem 4

In [ ]:
# paste here the image of the field.
# see if you can align the image to the other (problem 2) using np.rotate. Get as close as you can but only
# using 90 degree rotations and flips. (np.rotate, np.flip etc). Can you reproduce the exact image with just those? 
# If not, why do you think you cannot.
# load in the SA 112 field. Have the students identify 822 and 805. 
# then extract flux around that region


In [ ]:
from IPython.display import Image
Image("img/picture.png")

In [ ]:
from astropy.io import fits

