## Lab 1 part 2
Congratulations on successfully forking the lab and pulling it down. Now we can begin to do science. 

In this lab you will:
* Become familar with numpy arrays and indexing.
* Play with a real astronomical image.
* Extract data from that image, called the flux.


(Double click on this cell until the text changes. This language is called Markdown.)

### This lab is meant to be completed one cell at a time. You can evaluate each cell by pressing shift+enter. This contains a mix of cells that are instructional, and cells where I want you and your group members to collaborate on finding a solution. Problems will be indicated like this:

### Problem N:

In [17]:
# Some description of the problem. Insert your solution in this cell or between the cell above and below

End of problem N

### Numpy arrays and importing in Python

In [4]:
# We need to use numpy. In particular, things called arrays. 
# That is what numpy specializes in.
# Also, in python, anything preceded by a # is a comment. 
# Let us try to load in numpy, in particular, the arange function:
# https://numpy.org/doc/stable/reference/generated/numpy.arange.html

numpy.arange(5)

NameError: name 'numpy' is not defined

### Problem 1:

In [ ]:
# Why didn't the above cell work? Discuss and put your best (1 sentence) guess below (change the 
# cell type to Markdown):

End of problem 1.

In [ ]:
# Now lets do something that works:
import numpy
# this imports the numpy module, meaning now you can use it.
# Everything we use in python has to first be "imported" before we can use it.

In [6]:
print(numpy.arange(5))

[0 1 2 3 4]


In [7]:
# Yay! It worked. Arange creates an array of numbers up 
# to (but excluding) the number you choose.
# for instance, lets say I want an array from 5 to 9:
print(numpy.arange(5, 10))

[5 6 7 8 9]


In [10]:
# But I get tired of writing "numpy", so lets shorten things:
import numpy as np
# the "as" statement will import the entire package, but with a nickname. Any nickname works.
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [11]:
import numpy as somenickname
somenickname.arange(5, 10)

array([5, 6, 7, 8, 9])

In [15]:
# numpy has a rich amount of functionality. For instance, lets generate a random number that is either 0 or 1:
np.random.randint(0, 2)

0

### Problem 2:

End of problem 2